trigger: none

pool:
  vmImage: ubuntu-latest

steps:
# Publish the ASP.NET Core Application
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c release'
    zipAfterPublish: false

# Deploy the ASP.NET Core Application to AWS using CodeDeploy
- task: CodeDeployDeployApplication@1
  inputs:
    awsCredentials: 'AWS - DotNet Account'
    regionName: 'us-east-2'
    applicationName: 'DotNetCoreIIS'
    deploymentGroupName: 'DotNetCoreIIS'
    deploymentRevisionSource: 'workspace'
    revisionBundle: 'WebAppForDeploy/bin/release/net6.0/publish'
    bucketName: 'dotnet-deploy-demo'
    bundlePrefix: 'prod'
    description: 'Deploy DotNetCoreIIS'
    fileExistsBehavior: 'OVERWRITE'
    timeoutInMins: 180
- task: SendMessage@1
  inputs:
    awsCredentials: 'AWS - DotNet Account'
    regionName: 'us-east-2'
    messageTarget: 'queue'
    message: '{"Build":"DotNetToEC2"}'
    queueUrl: 'https://sqs.us-east-2.amazonaws.com/425173371283/AzureDevOpsBuild'