version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\wwwroot
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts\stopiis.ps1
      timeout: 5000    
  AfterInstall:
    - location: scripts\startiis.ps1
      timeout: 5000

